In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data/2024ReportCardData.csv", usecols=lambda col: not col.startswith('Unnamed'))

/var/folders/p6/tqnlcwnd075_z06_lxt45pv40000gn/T/ipykernel_92796/802293298.py:1: DtypeWarning: Columns (0: TSI_CSI, 1: TSI_CSI_Detail, 2: Math Proficiency, 3: English Proficiency, 4: US History Proficiency, 5: Science Proficiency, 6: Number of EL Students Proficient, 7: EL Growth, 8: Math Performance Level 1, 9: Math Performance Students Level 1, 10: Math Performance Level 2, 11: Math Performance Students Level 2, 12: Math Performance Level 3, 13: Math Performance Students Level 3, 14: Math Performance Level 4, 15: Math Performance Students Level 4, 16: Math Performance Level 5, 17: Math Performance Students Level 5, 18: English Performance Level 1, 19: English Performance Students Level 1, 20: English Performance Level 2, 21: English Performance Students Level 2, 22: English Performance Level 3, 23: English Performance Students Level 3, 24: English Performance Level 4, 25: English Performance Students Level 4, 26: English Performance Level 5, 27: English Performance Students Level 5, 28: Science Performance Level 1, 29: Science Performance Students Level 1, 30: Science Performance Level 2, 31: Science Performance Students Level 2, 32: Science Performance Level 3, 33: Science Performance Students Level 3, 34: Science Performance Level 4, 35: Science Performance Students Level 4, 36: Science Performance Level 5, 37: Science Performance Students Level 5, 38: Math Assessment Participation, 39: Number of Math Alternate Assessment Participation, 40: Math Alternate Assessment Participation, 41: English Assessment Participation, 42: Number of English Alternate Assessment Participation, 43: English Alternate Assessment Participation, 44: Science Assessment Participation, 45: Number of Science Alternate Assessment Participation, 46: Science Alternate Assessment Participation, 47: English Learners excluded, 48: In-School Suspension, 49: Out-of-School Suspension, 50: Expulsions, 51: % Chronic Absenteeism, 52: % of Advanced Course Participation, 53: Post-Secondary Enrollment, 54: Preschool Enrollment, 55: Preschool Enrollment Count) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("data/2024ReportCardData.csv", usecols=lambda col: not col.startswith('Unnamed'))

In [3]:
data.head(10)

,School_Year,District#,District_Name,School#,School_Name,Subgroup,Grade,Type,TSI_CSI,TSI_CSI_Detail,...,Assessment NAEP 8th Grade Reading - Advanced,Preschool Enrollment,Preschool Enrollment Count,Enrollment,Per-Pupil Expenditure,Per-Pupil District Level Funding Federal,Per-Pupil District Level Funding State/Local,Per-Pupil School Level Funding Federal,Per-Pupil School Level Funding State/Local,Per-Pupil Exclusions
0,2024,0,Mississippi,0,Mississippi,All,,State,NaN,NaN,...,2.0,<5%,11635,NaN,12367.33,NaN,NaN,NaN,NaN,NaN
1,2024,0,Mississippi,0,Mississippi,Female,,State,NaN,NaN,...,2.0,<5%,5595,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,0,Mississippi,0,Mississippi,Male,,State,NaN,NaN,...,1.0,<5%,6040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,0,Mississippi,0,Mississippi,Black or African American,,State,NaN,NaN,...,0.0,<5%,5549,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,0,Mississippi,0,Mississippi,White,,State,NaN,NaN,...,3.0,<5%,4506,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024,0,Mississippi,0,Mississippi,Alaskan Native or Native American,,State,NaN,NaN,...,0.0,<5%,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024,0,Mississippi,0,Mississippi,Asian,,State,NaN,NaN,...,0.0,<5%,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024,0,Mississippi,0,Mississippi,Hispanic or Latino,,State,NaN,NaN,...,1.0,<5%,646,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024,0,Mississippi,0,Mississippi,Native Hawaiian or Pacific Islander,,State,NaN,NaN,...,0.0,<5%,<10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024,0,Mississippi,0,Mississippi,Two or More Races,,State,NaN,NaN,...,5.0,<5%,831,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
districts = data[data["Type"] == "District"]
districts.head()

,School_Year,District#,District_Name,School#,School_Name,Subgroup,Grade,Type,TSI_CSI,TSI_CSI_Detail,...,Assessment NAEP 8th Grade Reading - Advanced,Preschool Enrollment,Preschool Enrollment Count,Enrollment,Per-Pupil Expenditure,Per-Pupil District Level Funding Federal,Per-Pupil District Level Funding State/Local,Per-Pupil School Level Funding Federal,Per-Pupil School Level Funding State/Local,Per-Pupil Exclusions
71,2024,130,Natchez-Adams School District,0,Natchez-Adams School District,All,C,District,NaN,NaN,...,NaN,<5%,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,2024,130,Natchez-Adams School District,0,Natchez-Adams School District,Female,C,District,NaN,NaN,...,NaN,<5%,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,2024,130,Natchez-Adams School District,0,Natchez-Adams School District,Male,C,District,NaN,NaN,...,NaN,<5%,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2024,130,Natchez-Adams School District,0,Natchez-Adams School District,Black or African American,C,District,NaN,NaN,...,NaN,<5%,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,2024,130,Natchez-Adams School District,0,Natchez-Adams School District,White,C,District,NaN,NaN,...,NaN,<5%,<10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
districts["District#"].nunique()

147

In [9]:
special_ed_district = districts[districts["Subgroup"].isin(["Students with Disabilities", "Students without Disabilities"])]
special_ed_district.head()

,School_Year,District#,District_Name,School#,School_Name,Subgroup,Grade,Type,TSI_CSI,TSI_CSI_Detail,...,Assessment NAEP 8th Grade Reading - Advanced,Preschool Enrollment,Preschool Enrollment Count,Enrollment,Per-Pupil Expenditure,Per-Pupil District Level Funding Federal,Per-Pupil District Level Funding State/Local,Per-Pupil School Level Funding Federal,Per-Pupil School Level Funding State/Local,Per-Pupil Exclusions
86,2024,130,Natchez-Adams School District,0,Natchez-Adams School District,Students with Disabilities,C,District,NaN,NaN,...,NaN,<5%,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2024,130,Natchez-Adams School District,0,Natchez-Adams School District,Students without Disabilities,C,District,NaN,NaN,...,NaN,<5%,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,2024,200,Alcorn School District,0,Alcorn School District,Students with Disabilities,A,District,NaN,NaN,...,NaN,<5%,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,2024,200,Alcorn School District,0,Alcorn School District,Students without Disabilities,A,District,NaN,NaN,...,NaN,<5%,129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,2024,220,Corinth School District,0,Corinth School District,Students with Disabilities,B,District,NaN,NaN,...,NaN,7.2,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
special_ed_district["District#"].nunique()

147

In [11]:
se_district_grad = special_ed_district[["District_Name", "Subgroup", "Graduation Rate"]]
se_district_grad

,District_Name,Subgroup,Graduation Rate
86,Natchez-Adams School District,Students with Disabilities,41.4
87,Natchez-Adams School District,Students without Disabilities,93.4
206,Alcorn School District,Students with Disabilities,65.2
207,Alcorn School District,Students without Disabilities,95.8
378,Corinth School District,Students with Disabilities,50.0
...,...,...,...
18613,Water Valley School District,Students without Disabilities,93.0
18672,Yazoo County School District,Students with Disabilities,NaN
18673,Yazoo County School District,Students without Disabilities,90.0
18765,Yazoo City Municipal School District,Students with Disabilities,25.8
18766,Yazoo City Municipal School District,Students without Disabilities,76.9

In [43]:
pivot = pd.pivot_table(se_district_grad, values = "Graduation Rate", index = "District_Name", columns = "Subgroup", aggfunc = "sum").reset_index()
pivot = pivot.rename(columns = {"Students with Disabilities": "Students_With_Disabilities", "Students without Disabilities": "Students_Without_Disabilities"})
pivot.sort_values("Students_With_Disabilities")

Subgroup,District_Name,Students_With_Disabilities,Students_Without_Disabilities
0,Aberdeen School District,0.0,92.1
49,Holly Springs School District,0.0,96.9
55,Jefferson County School District,0.0,92.6
56,Jefferson Davis County School District,0.0,90.8
57,Joel E. Smilow Collegiate,0.0,0.0
59,Kemper County School District,0.0,96.8
66,Leake County School District,0.0,85.0
68,Leflore Legacy Academy,0.0,0.0
69,Leland School District,0.0,90.5
74,MS School for the Blind and Deaf,0.0,0.0
79,Mdhs Division Of Youth Services,0.0,0.0
81,Midtown Public Charter School,0.0,0.0
85,Neshoba County School District,0.0,97.4
86,Nettleton School District,0.0,94.7
88,Newton County School District,0.0,93.6
89,Newton Municipal School District,0.0,97.5
90,North Bolivar Consolidated School District,0.0,77.8
96,Okolona Separate School District,0.0,91.9
110,Quitman County School District,0.0,87.8
113,Reimagine Prep,0.0,0.0
114,Richton School District,0.0,95.7
118,Smilow Prep,0.0,0.0
120,South Delta School District,0.0,97.1
129,Tunica County School District,0.0,91.1
132,Union Public School District,0.0,100.0
135,Water Valley School District,0.0,93.0
137,Webster County School District,0.0,87.5
138,West Bolivar Consolidated School District,0.0,80.3
141,West Tallahatchie School District,0.0,89.7
144,Winona-Montgomery Consolidated District,0.0,80.9
48,Hollandale School District,0.0,94.1
35,Forrest County School District,0.0,97.6
146,Yazoo County School District,0.0,90.0
31,East Tallahatchie Consolidated School District,0.0,88.1
2,Ambition Preparatory,0.0,0.0
18,Clarksdale Collegiate,0.0,0.0
3,Amite County School District,0.0,90.0
17,Claiborne County School District,0.0,94.9
5,Attala County School District,0.0,92.5
6,Baldwyn School District,0.0,77.1
22,Coahoma County School District,0.0,94.8
14,Carroll County School District,0.0,90.7
10,Booneville School District,0.0,93.3
30,East Jasper Consolidated School District,0.0,93.8
122,South Pike School District,18.2,84.2
143,Wilkinson County School District,23.1,79.2
145,Yazoo City Municipal School District,25.8,76.9
142,Western Line School District,27.3,78.5
19,Clarksdale Municipal School District,28.6,85.3
46,Hazlehurst City School District,30.0,83.3
140,West Point Consolidated School District,30.0,82.6
94,Noxubee County School District,35.7,88.2
91,North Panola School District,35.7,85.7
23,Coffeeville School District,36.4,89.7
136,Wayne County School District,38.5,96.3
33,Forest Municipal School District,38.5,83.9
20,Cleveland School District,38.9,81.6
84,Natchez-Adams School District,41.4,93.4
47,Hinds County School District,44.9,88.4
126,Sunflower County Consolidate School District,45.8,89.0
64,Laurel School District,46.2,85.9
130,Tupelo Public School District,47.4,88.0
92,North Pike School District,47.4,91.9
15,Chickasaw County School District,47.4,96.9
11,Brookhaven School District,47.6,86.9
42,Gulfport School District,48.5,92.6
67,Lee County School District,48.6,89.1
26,Copiah County School District,50.0,90.7
134,Walthall County School District,50.0,84.7
39,Greenville Public School District,50.0,82.1
27,Corinth School District,50.0,96.0
28,Covington County School District,51.4,89.0
21,Clinton Public School District,51.7,92.4
65,Lawrence County School District,52.6,85.2
77,Marshall County School District,53.3,90.6
50,Holmes Consolidated School District,54.5,94.5
13,Canton Public School District,54.5,77.5
116,Senatobia Municipal School District,54.5,94.2
117,Simpson County School District,54.5,87.3
82,Monroe County School District,55.6,92.5
25,Columbus Municipal School District,56.0,87.8
127,Tate County School District,56.3,88.5
80,Meridian Public School District,56.7,85.8
36,Franklin County School District,57.7,98.8
115,Scott County School District,57.9,86.6
102,Perry County School District,60.0,82.1
104,Philadelphia Public School District,60.0,87.8
124,Starkville- Oktibbeha Consolidated School Dist...,60.7,90.8
109,Prentiss County School District,61.1,95.5
119,Smith County School District,61.3,90.8
43,Hancock County School District,62.2,92.3
41,Grenada School District,62.5,94.1
76,Marion County School District,63.2,88.8
24,Columbia School District,63.2,98.9
51,Humphreys County School District,63.6,75.6
62,Lamar County School District,64.1,94.9
131,Union County School District,64.3,93.1
61,Lafayette County School District,64.3,97.1
1,Alcorn School District,65.2,95.8
105,Picayune School District,65.2,81.9
101,Pearl River County School District,65.5,93.0
133,Vicksburg Warren School District,65.9,95.6
54,Jackson Public School District,66.0,85.9
44,Harrison County School District,66.7,88.8
60,Kosciusko School District,66.7,92.1
97,Oxford School District,68.3,93.2
40,Greenwood-Leflore Consolidated School District,68.6,84.3
53,Jackson County School District,68.7,97.0
78,Mccomb School District,68.8,85.2
52,Itawamba County School District,68.8,95.4
72,Louisville Municipal School District,69.2,96.3
75,Madison County School District,69.7,93.8
45,Hattiesburg Public School District,70.0,96.7
83,Moss Point Separate School District,70.0,94.6
112,Rankin County School District,70.1,96.7
98,Pascagoula Gautier School District,70.2,91.9
107,Pontotoc County School District,70.8,90.3
125,Stone County School District,72.2,93.5
58,Jones County School District,72.8,95.3
70,Lincoln County School District,74.1,90.6
128,Tishomingo County School District,74.1,93.1
87,New Albany Public Schools,75.0,94.5
7,Bay St Louis Waveland School District,75.0,96.7
4,Amory School District,75.0,93.1
106,Pontotoc City School District,75.0,89.9
63,Lauderdale County School District,75.0,98.9
9,Biloxi Public School District,77.5,92.6
16,Choctaw County School District,78.6,96.4
73,Lowndes County School District,79.7,94.1
95,Ocean Springs School District,80.0,94.7
103,Petal School District,80.4,98.8
34,Forrest County Agricultural High School,80.6,92.5
139,West Jasper Consolidated Schools,80.8,97.2
121,South Panola School District,81.8,92.6
71,Long Beach School District,81.8,97.3
99,Pass Christian Public School District,81.8,94.9
93,North Tippah School District,83.3,97.6
123,South Tippah School District,83.7,98.9
37,George County School District,83.9,97.2
100,Pearl Public School District,84.0,96.4
12,Calhoun County School District,86.7,89.7
29,Desoto County School District,87.3,98.0
111,Quitman School District,90.0,96.3
8,Benton County School District,90.0,98.1
32,Enterprise School District,90.9,97.1
38,Greene County School District,100.0,92.3
108,Poplarville Separate School District,100.0,95.6

In [ ]:
pivo

## Takeaway 

44 school districts (approximately 30% of MS school districts) have a "0%" graduation rate for students with disabilities, indicating there either are no students with disabilities or there is missing data. Recommended next steps are to determine why these zero values exist. 

If a school district doesn't have any students with disabilities, it could be an indication students aren't tested and/or diagnosed for disabilities and therefore aren't given the specialized education they need. Could be interesting to see if the entire student body's grades indicate this as a possibility.

In [23]:
pd.reset_option('display.max_rows')

In [ ]:
#remove zero/missing values for now
dis_df = pivot[pivot.Students_With_Disabilities != 0.0]
dis_df["Grad Rate % Difference"] = ((dis_df["Students_With_Disabilities"] - dis_df["Students_Without_Disabilities"]) / dis_df["Students_Without_Disabilities"]) * 100

In [42]:
pd.set_option('display.max_rows', None)
dis_df

Subgroup,District_Name,Students_With_Disabilities,Students_Without_Disabilities,Grad Rate % Difference
1,Alcorn School District,65.2,95.8,-31.941545
4,Amory School District,75.0,93.1,-19.441461
7,Bay St Louis Waveland School District,75.0,96.7,-22.440538
8,Benton County School District,90.0,98.1,-8.256881
9,Biloxi Public School District,77.5,92.6,-16.306695
11,Brookhaven School District,47.6,86.9,-45.224396
12,Calhoun County School District,86.7,89.7,-3.344482
13,Canton Public School District,54.5,77.5,-29.677419
15,Chickasaw County School District,47.4,96.9,-51.083591
16,Choctaw County School District,78.6,96.4,-18.464730
19,Clarksdale Municipal School District,28.6,85.3,-66.471278
20,Cleveland School District,38.9,81.6,-52.328431
21,Clinton Public School District,51.7,92.4,-44.047619
23,Coffeeville School District,36.4,89.7,-59.420290
24,Columbia School District,63.2,98.9,-36.097068
25,Columbus Municipal School District,56.0,87.8,-36.218679
26,Copiah County School District,50.0,90.7,-44.873208
27,Corinth School District,50.0,96.0,-47.916667
28,Covington County School District,51.4,89.0,-42.247191
29,Desoto County School District,87.3,98.0,-10.918367
32,Enterprise School District,90.9,97.1,-6.385170
33,Forest Municipal School District,38.5,83.9,-54.112038
34,Forrest County Agricultural High School,80.6,92.5,-12.864865
36,Franklin County School District,57.7,98.8,-41.599190
37,George County School District,83.9,97.2,-13.683128
38,Greene County School District,100.0,92.3,8.342362
39,Greenville Public School District,50.0,82.1,-39.098660
40,Greenwood-Leflore Consolidated School District,68.6,84.3,-18.623962
41,Grenada School District,62.5,94.1,-33.581296
42,Gulfport School District,48.5,92.6,-47.624190
43,Hancock County School District,62.2,92.3,-32.611051
44,Harrison County School District,66.7,88.8,-24.887387
45,Hattiesburg Public School District,70.0,96.7,-27.611169
46,Hazlehurst City School District,30.0,83.3,-63.985594
47,Hinds County School District,44.9,88.4,-49.208145
50,Holmes Consolidated School District,54.5,94.5,-42.328042
51,Humphreys County School District,63.6,75.6,-15.873016
52,Itawamba County School District,68.8,95.4,-27.882600
53,Jackson County School District,68.7,97.0,-29.175258
54,Jackson Public School District,66.0,85.9,-23.166473
58,Jones County School District,72.8,95.3,-23.609654
60,Kosciusko School District,66.7,92.1,-27.578719
61,Lafayette County School District,64.3,97.1,-33.779609
62,Lamar County School District,64.1,94.9,-32.455216
63,Lauderdale County School District,75.0,98.9,-24.165824
64,Laurel School District,46.2,85.9,-46.216531
65,Lawrence County School District,52.6,85.2,-38.262911
67,Lee County School District,48.6,89.1,-45.454545
70,Lincoln County School District,74.1,90.6,-18.211921
71,Long Beach School District,81.8,97.3,-15.930113
72,Louisville Municipal School District,69.2,96.3,-28.141225
73,Lowndes County School District,79.7,94.1,-15.302869
75,Madison County School District,69.7,93.8,-25.692964
76,Marion County School District,63.2,88.8,-28.828829
77,Marshall County School District,53.3,90.6,-41.169978
78,Mccomb School District,68.8,85.2,-19.248826
80,Meridian Public School District,56.7,85.8,-33.916084
82,Monroe County School District,55.6,92.5,-39.891892
83,Moss Point Separate School District,70.0,94.6,-26.004228
84,Natchez-Adams School District,41.4,93.4,-55.674518
87,New Albany Public Schools,75.0,94.5,-20.634921
91,North Panola School District,35.7,85.7,-58.343057
92,North Pike School District,47.4,91.9,-48.422198
93,North Tippah School District,83.3,97.6,-14.651639
94,Noxubee County School District,35.7,88.2,-59.523810
95,Ocean Springs School District,80.0,94.7,-15.522703
97,Oxford School District,68.3,93.2,-26.716738
98,Pascagoula Gautier School District,70.2,91.9,-23.612622
99,Pass Christian Public School District,81.8,94.9,-13.804004
100,Pearl Public School District,84.0,96.4,-12.863071
101,Pearl River County School District,65.5,93.0,-29.569892
102,Perry County School District,60.0,82.1,-26.918392
103,Petal School District,80.4,98.8,-18.623482
104,Philadelphia Public School District,60.0,87.8,-31.662870
105,Picayune School District,65.2,81.9,-20.390720
106,Pontotoc City School District,75.0,89.9,-16.573971
107,Pontotoc County School District,70.8,90.3,-21.594684
108,Poplarville Separate School District,100.0,95.6,4.602510
109,Prentiss County School District,61.1,95.5,-36.020942
111,Quitman School District,90.0,96.3,-6.542056
112,Rankin County School District,70.1,96.7,-27.507756
115,Scott County School District,57.9,86.6,-33.140878
116,Senatobia Municipal School District,54.5,94.2,-42.144374
117,Simpson County School District,54.5,87.3,-37.571592
119,Smith County School District,61.3,90.8,-32.488987
121,South Panola School District,81.8,92.6,-11.663067
122,South Pike School District,18.2,84.2,-78.384798
123,South Tippah School District,83.7,98.9,-15.369060
124,Starkville- Oktibbeha Consolidated School Dist...,60.7,90.8,-33.149780
125,Stone County School District,72.2,93.5,-22.780749
126,Sunflower County Consolidate School District,45.8,89.0,-48.539326
127,Tate County School District,56.3,88.5,-36.384181
128,Tishomingo County School District,74.1,93.1,-20.408163
130,Tupelo Public School District,47.4,88.0,-46.136364
131,Union County School District,64.3,93.1,-30.934479
133,Vicksburg Warren School District,65.9,95.6,-31.066946
134,Walthall County School District,50.0,84.7,-40.968123
136,Wayne County School District,38.5,96.3,-60.020768
139,West Jasper Consolidated Schools,80.8,97.2,-16.872428
140,West Point Consolidated School District,30.0,82.6,-63.680387
142,Western Line School District,27.3,78.5,-65.222930
143,Wilkinson County School District,23.1,79.2,-70.833333
145,Yazoo City Municipal School District,25.8,76.9,-66.449935

In [34]:
dis_df.describe()

Subgroup,Students_With_Disabilities,Students_Without_Disabilities,Grad Rate % Difference
count,103.000000,103.000000,103.000000
mean,62.087379,91.125243,-32.342947
std,17.304871,5.567971,17.092721
min,18.200000,75.600000,-78.384798
25%,50.000000,87.800000,-43.187831
50%,64.100000,92.500000,-30.934479
75%,74.550000,95.600000,-19.345144
max,100.000000,98.900000,8.342362

In [39]:
disability_rt_below_mean = dis_df[dis_df["Students_With_Disabilities"] < 62.087379]
disability_rt_below_mean.sort_values("Students_With_Disabilities")

Subgroup,District_Name,Students_With_Disabilities,Students_Without_Disabilities,Grad Rate % Difference
122,South Pike School District,18.2,84.2,-78.384798
143,Wilkinson County School District,23.1,79.2,-70.833333
145,Yazoo City Municipal School District,25.8,76.9,-66.449935
142,Western Line School District,27.3,78.5,-65.222930
19,Clarksdale Municipal School District,28.6,85.3,-66.471278
46,Hazlehurst City School District,30.0,83.3,-63.985594
140,West Point Consolidated School District,30.0,82.6,-63.680387
91,North Panola School District,35.7,85.7,-58.343057
94,Noxubee County School District,35.7,88.2,-59.523810
23,Coffeeville School District,36.4,89.7,-59.420290
33,Forest Municipal School District,38.5,83.9,-54.112038
136,Wayne County School District,38.5,96.3,-60.020768
20,Cleveland School District,38.9,81.6,-52.328431
84,Natchez-Adams School District,41.4,93.4,-55.674518
47,Hinds County School District,44.9,88.4,-49.208145
126,Sunflower County Consolidate School District,45.8,89.0,-48.539326
64,Laurel School District,46.2,85.9,-46.216531
15,Chickasaw County School District,47.4,96.9,-51.083591
130,Tupelo Public School District,47.4,88.0,-46.136364
92,North Pike School District,47.4,91.9,-48.422198
11,Brookhaven School District,47.6,86.9,-45.224396
42,Gulfport School District,48.5,92.6,-47.624190
67,Lee County School District,48.6,89.1,-45.454545
39,Greenville Public School District,50.0,82.1,-39.098660
134,Walthall County School District,50.0,84.7,-40.968123
26,Copiah County School District,50.0,90.7,-44.873208
27,Corinth School District,50.0,96.0,-47.916667
28,Covington County School District,51.4,89.0,-42.247191
21,Clinton Public School District,51.7,92.4,-44.047619
65,Lawrence County School District,52.6,85.2,-38.262911
77,Marshall County School District,53.3,90.6,-41.169978
13,Canton Public School District,54.5,77.5,-29.677419
117,Simpson County School District,54.5,87.3,-37.571592
50,Holmes Consolidated School District,54.5,94.5,-42.328042
116,Senatobia Municipal School District,54.5,94.2,-42.144374
82,Monroe County School District,55.6,92.5,-39.891892
25,Columbus Municipal School District,56.0,87.8,-36.218679
127,Tate County School District,56.3,88.5,-36.384181
80,Meridian Public School District,56.7,85.8,-33.916084
36,Franklin County School District,57.7,98.8,-41.599190
115,Scott County School District,57.9,86.6,-33.140878
104,Philadelphia Public School District,60.0,87.8,-31.662870
102,Perry County School District,60.0,82.1,-26.918392
124,Starkville- Oktibbeha Consolidated School Dist...,60.7,90.8,-33.149780
109,Prentiss County School District,61.1,95.5,-36.020942
119,Smith County School District,61.3,90.8,-32.488987

In [40]:
disability_rt_below_mean.info()

<class 'pandas.DataFrame'>
Index: 46 entries, 11 to 145
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   District_Name                  46 non-null     str
 1   Students_With_Disabilities     46 non-null     float64
 2   Students_Without_Disabilities  46 non-null     float64
 3   Grad Rate % Difference         46 non-null     float64
dtypes: float64(3), str(1)
memory usage: 1.8 KB

46 school districts (appx 30%) have lower graduation rates for students with disabilities than the state average

In [32]:
top_10_diff = dis_df.sort_values("Grad Rate % Difference").head(20)
top_10_diff

Subgroup,District_Name,Students_With_Disabilities,Students_Without_Disabilities,Grad Rate % Difference
122,South Pike School District,18.2,84.2,-78.384798
143,Wilkinson County School District,23.1,79.2,-70.833333
19,Clarksdale Municipal School District,28.6,85.3,-66.471278
145,Yazoo City Municipal School District,25.8,76.9,-66.449935
142,Western Line School District,27.3,78.5,-65.222930
46,Hazlehurst City School District,30.0,83.3,-63.985594
140,West Point Consolidated School District,30.0,82.6,-63.680387
136,Wayne County School District,38.5,96.3,-60.020768
94,Noxubee County School District,35.7,88.2,-59.523810
23,Coffeeville School District,36.4,89.7,-59.420290
91,North Panola School District,35.7,85.7,-58.343057
84,Natchez-Adams School District,41.4,93.4,-55.674518
33,Forest Municipal School District,38.5,83.9,-54.112038
20,Cleveland School District,38.9,81.6,-52.328431
15,Chickasaw County School District,47.4,96.9,-51.083591
47,Hinds County School District,44.9,88.4,-49.208145
126,Sunflower County Consolidate School District,45.8,89.0,-48.539326
92,North Pike School District,47.4,91.9,-48.422198
27,Corinth School District,50.0,96.0,-47.916667
42,Gulfport School District,48.5,92.6,-47.624190

In [ ]:
Average graduation rate for students with disabilites 
Average graduation rate for students without disabilities 
Average difference

SyntaxError: invalid syntax (4272988531.py, line 1)

# Takeaway

Students without disabilities graduate at at least twice the rate of students with disabilities in 15 Mississippi school districts